### ISSUE TITLE
question about sending sysex messages to the SY-300

### ISSUE THREAD

**Issue by dtenenba** [ElliotGarbus/SY300Panel#5]
Hi,

I think I want to make a little app that handles the operation of the SY-300 Blender feature.

The reason for this is that the Blender feature is the only one that I am aware of that you cannot access from Boss Tone Studio for SY-300 (or from your app). And I use it frequently. So it's the only reason why the SY-300 is still on my desk, and not on the floor where I can use it as a pedal. 

I think between your code and the MIDI Implementation document I should be able to figure out how to do this. I've got plenty of experience with python and writing code related to midi (though not sysex messages so much). 

My question is how you determined what address to send your messages to. What's in the code does not seem to match what's in the implementation document. For example, [here](https://github.com/ElliotGarbus/SY300Panel/blob/touch_update_00/sy300midi.py#L43) you have an example where you set OSC1's type to be Noise. 

The address you're sending to is `[0x20, 0x00, 0x20, 0x1]` and the value you are sending is `[6]`.
I get that 6 is the value for the Noise setting. 
The doc says the address for setting an oscillator's waveform is `00 01` which does not match what you have unless you ignore the `20`s. Also, the doc doesn't say how to specify which oscillator you are trying to change. Also, there appear to be multiple features with the same address of `00 01`, so how does the SY300 know that you mean change the waveform of osc1?

Would you mind sharing a quick explanation of how you came up with this address, or more generally how to make use of the addresses provided in the doc? 

Also, why is it that when I send data to the SY300 in an IPython session, I see the Bulk Data Receiving Screen on the unit each 
time, but when I run your app, I only see that when I close the app?

TIA!

If you like you can send me a PM on vguitar (I am dandante there).

**Comment by ElliotGarbus** [comment]
Dan,
To find an address for the Sysex you need to start on pg 6 of the SY-300 MIDI Implementation.  This page is titled System Exclusive Address Map. 
Notice at the top of the page the first set of addresses are referred to as starting addresses.  Setup, System, Patch (Temporary)…
You will also notice the other address tables are labeled "Offset Address".  You need to combine the start and offsets to create a full address. 

Therefore:
20 00 20 01 
20 00 00 00 - Start Address for Patch (Temporary), you can think if this as working memory
00  00 20 00 - Offset for OSC 1, this is also on page 6 under patch
00  00 00 01 - Offset for OSC Waveform on pg 53 under Patch Oscillator Parameters Offset Address

In the document they omit the leading zeros.  I have included them here to simplify the formatting.
I hope that makes it clear how to address the SYSEX components in the SY300.  One of the interesting consequences of this model is that you can also do block transfers of data.   Feel free to ask any follow-up questions.

_Also, why is it that when I send data to the SY300 in an IPython session, I see the Bulk Data Receiving Screen on the unit each
time, but when I run your app, I only see that when I close the app?_

There is an undocumented verbose mode in the SY300.  Notice in my code: 
https://github.com/ElliotGarbus/SY300Panel/blob/782a2273ca5946050b16aa21c979697a02313499/main.py#L121
          
This sets the SY300 into editor mode or verbose mode, and suppresses the Bulk Data message on the SY300 display.
I turn this mode off when the app is exiting, see:
https://github.com/ElliotGarbus/SY300Panel/blob/782a2273ca5946050b16aa21c979697a02313499/main.py#L132

This was my first program using mido, and my first serious kivy program.  I have learned quite a few things since this code was written - if something looks odd - feel free to ask.

Good Luck with your project!

**Comment by dtenenba** [comment]
Thank you for the response! Under "Therefore" above you say "20 00 20 10" - is that a typo that should say "20 00 20 01"? Because the latter is the message you are sending in your code and the way I interpret what you are saying -- 01 is the offset for OSC waveform and aside from it everything else in that "column" is 0....

**Comment by ElliotGarbus** [comment]
Of course you are correct... I'll edit the post to fix it.

**Comment by dtenenba** [comment]
Thanks again for your reply, that was the rosetta stone I needed, I'm now able to control the blender from Python, now I just need a UI.
